name: TheTowersPlugin
version: 1.0
author: Loyso
main: fr.loyso.ttplugin.Plugin

commands:
    ping:
        description: Testing command
        usage: /ping
    newgame:
            description: WIP
            usage: /newgame
    stoptest:
                description: WIP
                usage: /stoptest