name: TheTowersPlugin
version: 1.0
author: Loyso
main: fr.loyso.ttplugin.Plugin

commands:
    ping:
        description: Returns "Pong!"
        usage: /ping
    newgame:
            description: Regenerates a new map
            usage: /newgame
    startgame:
            description: WIP
            usage: /startgame
    leaveobservers:
            description: Leave the observers
            usage: /leaveobservers